#!/usr/bin/env python3
"""Post-process a built pkgdown site for search engines.

pkgdown 2.2 has no hook for a per-page canonical link or og:url, no way to
mark a page noindex on its own, no description for its index, news, authors
and license pages, drops the ``description:`` of Quarto articles, and lists
every HTML file in sitemap.xml. This runs between "Build site" and "Deploy"
in .github/workflows/pkgdown.yaml and fills those gaps in place:

* every page pkgdown generated (marker ``<!-- Generated by pkgdown``) that is
  not a redirect stub gets ``<link rel="canonical">`` and ``og:url``;
* 404.html and reference topics whose Rd carries ``\\keyword{internal}`` get
  ``<meta name="robots" content="noindex">``;
* pages without a ``<meta name="description">`` get one from a small map,
  or from the ``description:`` field of the matching ``.qmd`` article;
* sitemap.xml drops 404.html, LICENSE*.html and every page marked noindex,
  and lists the root index.html as the bare site URL;
* every page gets a Dublin Core block, so a reference manager saving it
  records the real title, authors, publisher and date instead of falling
  back to the ``<title>`` alone.

Usage: python3 tools/seo-postprocess.py <site-dir> <base-url>

Standard library only, and idempotent: a tag that is already present is
never inserted twice, so the script can run on an already processed site.
"""

from __future__ import annotations

import html
import re
import subprocess
import sys
from pathlib import Path
from xml.etree import ElementTree

MARKER = "<!-- Generated by pkgdown"
NOINDEX = '<meta name="robots" content="noindex">'
SITEMAP_NS = "http://www.sitemaps.org/schemas/sitemap/0.9"

# Dublin Core. Zotero's Embedded Metadata translator looks for Highwire Press
# ``citation_*`` tags first, then Dublin Core, then Open Graph, and finally
# falls back to ``<title>`` with no author and no date.
#
# We deliberately do not emit ``citation_*``: Google Scholar reserves those for
# scholarly articles and says they must not carry a repository or site name, so
# putting them on package documentation misrepresents the page and risks the
# site being dropped from Scholar. The two MAIDR papers stay cited by DOI in
# the home page's JSON-LD, in inst/CITATION and in the visible citation
# section, and are indexed in Scholar through their publishers.
PUBLISHER = "(x)Ability Design Lab, University of Illinois Urbana-Champaign"

# Surname-first so Zotero splits each into first and last names rather than
# storing the whole string as a single-field name. Matches Authors@R in
# DESCRIPTION.
CREATORS = ["Seo, JooYoung", "Kalaiselvan, Niranjan"]

# SPDX form of DESCRIPTION's "GPL (>= 3)".
RIGHTS = "GPL-3.0-or-later"

TITLE_RE = re.compile(r"<title>(?P<title>.*?)</title>", re.S)
DESCRIPTION_RE = re.compile(
    r'<meta\s+name="description"\s+content="(?P<content>[^"]*)"', re.I
)

# Pages pkgdown builds without any description, keyed by site-relative path.
DESCRIPTIONS = {
    "news/index.html": (
        "Changelog for the maidr R package: new accessible plot types, bug "
        "fixes and improvements in each release."
    ),
    "authors.html": (
        "Authors and maintainer of the maidr R package, and how to cite it."
    ),
    "reference/index.html": (
        "Function reference for the maidr R package: show(), save_html(), "
        "maidr_on(), maidr_output(), render_maidr() and the other exported "
        "functions."
    ),
    "articles/index.html": (
        "Articles for the maidr R package: getting started, accessible "
        "plot examples by family, and Shiny integration."
    ),
    "LICENSE.html": (
        "GNU General Public License version 3, the license of the maidr R "
        "package."
    ),
}


def page_url(base: str, rel: str) -> str:
    """The canonical URL of a site-relative path.

    The root index.html is the bare site URL; an index.html inside a
    sub-directory keeps its literal name, which is how pkgdown links to it.
    """
    if rel == "index.html":
        return base + "/"
    return base + "/" + rel


def insert_before_head_end(text: str, tags: list[str]) -> str:
    """Insert ``tags`` just before the first ``</head>``."""
    if not tags:
        return text
    idx = text.find("</head>")
    if idx < 0:
        return text
    return text[:idx] + "".join(tag + "\n" for tag in tags) + text[idx:]


def rd_is_internal(root: Path, rel: str) -> bool:
    """Whether reference/<name>.html documents a ``\\keyword{internal}`` topic."""
    if not rel.startswith("reference/") or rel == "reference/index.html":
        return False
    rd = root / "man" / (Path(rel).stem + ".Rd")
    if not rd.is_file():
        return False
    return "\\keyword{internal}" in rd.read_text(encoding="utf-8", errors="replace")


def yaml_description(qmd: Path) -> str | None:
    """The ``description:`` of a Quarto article's YAML header, if any.

    Handles a quoted or bare single-line value and a ``>``/``>-``/``|`` block
    scalar, which is all these vignettes use; anything else is left alone.
    """
    if not qmd.is_file():
        return None
    lines = qmd.read_text(encoding="utf-8").split("\n")
    if not lines or lines[0].strip() != "---":
        return None
    try:
        end = lines.index("---", 1)
    except ValueError:
        return None
    header = lines[1:end]
    for i, line in enumerate(header):
        match = re.match(r"^description:\s*(.*)$", line)
        if not match:
            continue
        value = match.group(1).strip()
        if value in (">", ">-", "|", "|-"):
            block = []
            for cont in header[i + 1 :]:
                if cont.strip() == "" or cont.startswith((" ", "\t")):
                    block.append(cont.strip())
                else:
                    break
            return " ".join(part for part in block if part) or None
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        return value or None
    return None


def description_for(root: Path, rel: str) -> str | None:
    if rel in DESCRIPTIONS:
        return DESCRIPTIONS[rel]
    if rel.startswith("articles/") and rel.endswith(".html"):
        name = Path(rel).stem
        for candidate in (
            root / "vignettes" / "articles" / f"{name}.qmd",
            root / "vignettes" / f"{name}.qmd",
        ):
            desc = yaml_description(candidate)
            if desc:
                return desc
    return None


_DATE_CACHE: dict[str, str] = {}
_HISTORY_CACHE: dict[Path, bool] = {}


def has_history(root: Path) -> bool:
    """Whether ``root`` holds enough history to date a file by.

    A depth-1 checkout has a single commit with no parent, so git treats every
    tracked path as added by it and ``git log -1 -- <path>`` reports that one
    commit for all of them -- every page would carry the build date while
    looking correctly per-page. A wrong date that looks right is worse than
    none, so that case is reported rather than dated.

    Being shallow is not itself the problem: a checkout deepened to many
    commits still distinguishes the files changed recently, which is what the
    dates are for. Only the single-commit case is unusable.
    """
    if root in _HISTORY_CACHE:
        return _HISTORY_CACHE[root]
    try:
        run = subprocess.run(
            ["git", "rev-list", "--count", "HEAD"],
            cwd=root,
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError:
        return False
    usable = False
    if run.returncode == 0:
        try:
            usable = int(run.stdout.strip()) > 1
        except ValueError:
            usable = False
    if not usable:
        print(
            "seo-postprocess: single-commit checkout, omitting DC.date "
            "(set fetch-depth: 0 on the checkout step)",
            file=sys.stderr,
        )
    _HISTORY_CACHE[root] = usable
    return usable


def git_date(root: Path, rel_path: str) -> str:
    """Last commit date for ``rel_path``, or "" when git cannot answer.

    Cached: the site has hundreds of pages and many share a source, so an
    uncached lookup would shell out to git once per page.
    """
    if rel_path in _DATE_CACHE:
        return _DATE_CACHE[rel_path]
    try:
        run = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", rel_path],
            cwd=root,
            capture_output=True,
            text=True,
            check=False,
        )
        date = run.stdout.strip() if run.returncode == 0 else ""
    except OSError:
        date = ""
    _DATE_CACHE[rel_path] = date
    return date


def source_date(root: Path, rel: str) -> str:
    """Date for the built page ``rel``, taken from the file it was built from.

    pkgdown builds each page from a source elsewhere in the repository: the
    home page from README.md, an article from its vignette, a reference topic
    from its Rd. A page whose source cannot be located falls back to the
    package metadata, which changes with every release.
    """
    if not has_history(root):
        return ""
    stem = Path(rel).stem
    if rel == "index.html":
        candidates = ["README.md"]
    elif rel.startswith("articles/"):
        candidates = [
            f"vignettes/articles/{stem}.qmd",
            f"vignettes/articles/{stem}.Rmd",
            f"vignettes/{stem}.Rmd",
            f"vignettes/{stem}.qmd",
        ]
    elif rel.startswith("reference/"):
        candidates = [f"man/{stem}.Rd"]
    elif rel.startswith("news/"):
        candidates = ["NEWS.md"]
    else:
        candidates = []

    for candidate in candidates:
        if (root / candidate).exists():
            date = git_date(root, candidate)
            if date:
                return date
    return git_date(root, "DESCRIPTION")


def dublin_core_tags(
    title: str, description: str, url: str, date: str, rel: str
) -> list[str]:
    """Dublin Core tags for one page.

    ``DC.type`` is a Dublin Core Type Vocabulary term. The home page stands for
    the package itself and so is ``Software``; every other page is
    documentation about it and is ``Text``. Claiming ``Software`` site-wide
    would tell a reference manager that a reference topic is the program.
    """
    pairs: list[tuple[str, str]] = [("DC.title", title)]
    pairs += [("DC.creator", creator) for creator in CREATORS]
    pairs.append(("DC.publisher", PUBLISHER))
    if description:
        pairs.append(("DC.description", description))
    pairs += [
        ("DC.identifier", url),
        ("DC.type", "Software" if rel == "index.html" else "Text"),
        ("DC.format", "text/html"),
        ("DC.language", "en"),
        ("DC.rights", RIGHTS),
    ]
    if date:
        pairs.append(("DC.date", date))
    return [
        f'<meta name="{name}" content="{html.escape(content, quote=True)}">'
        for name, content in pairs
    ]


def process_page(root: Path, site: Path, path: Path, base: str, stats: dict) -> None:
    text = path.read_text(encoding="utf-8")
    if MARKER not in text or 'http-equiv="refresh"' in text:
        stats["skipped"] += 1
        return
    rel = path.relative_to(site).as_posix()
    url = page_url(base, rel)
    tags: list[str] = []

    if 'rel="canonical"' not in text:
        tags.append(f'<link rel="canonical" href="{html.escape(url, quote=True)}">')
        stats["canonical"] += 1
    if 'property="og:url"' not in text:
        tags.append(f'<meta property="og:url" content="{html.escape(url, quote=True)}">')

    noindex = rel == "404.html" or rd_is_internal(root, rel)
    if noindex:
        stats["noindex_paths"].add(rel)
        if 'name="robots"' not in text:
            tags.append(NOINDEX)
            stats["noindex"] += 1

    description = ""
    existing = DESCRIPTION_RE.search(text)
    if existing:
        description = html.unescape(existing.group("content"))
    else:
        desc = description_for(root, rel)
        if desc:
            description = desc
            escaped = html.escape(desc, quote=True)
            tags.append(f'<meta name="description" content="{escaped}">')
            if 'property="og:description"' not in text:
                tags.append(f'<meta property="og:description" content="{escaped}">')
            stats["description"] += 1

    if 'name="DC.' not in text:
        title_match = TITLE_RE.search(text)
        if title_match:
            # pkgdown renders "<page title> • <package>"; the suffix is site
            # furniture, and a reference manager should record the page's own
            # title.
            title = html.unescape(title_match.group("title")).strip()
            title = re.split(r"\s+[•|]\s+", title)[0].strip() or title
            tags.extend(
                dublin_core_tags(
                    title, description, url, source_date(root, rel), rel
                )
            )
            stats["dublin_core"] += 1

    if tags:
        path.write_text(insert_before_head_end(text, tags), encoding="utf-8")
    stats["processed"] += 1


def rewrite_sitemap(site: Path, base: str, noindex_paths: set[str], stats: dict) -> None:
    sitemap = site / "sitemap.xml"
    if not sitemap.is_file():
        stats["sitemap"] = "absent"
        return
    tree = ElementTree.parse(sitemap)
    urlset = tree.getroot()
    ns = {"sm": SITEMAP_NS}
    entries = urlset.findall("sm:url", ns)
    before = len(entries)
    dropped = {"404.html", "LICENSE.html", "LICENSE-text.html"} | noindex_paths
    prefix = base + "/"
    for entry in entries:
        loc = entry.find("sm:loc", ns)
        if loc is None or not loc.text:
            urlset.remove(entry)
            continue
        text = loc.text.strip()
        rel = text[len(prefix) :] if text.startswith(prefix) else text
        if rel in dropped:
            urlset.remove(entry)
        elif rel == "index.html":
            loc.text = page_url(base, rel)
    ElementTree.register_namespace("", SITEMAP_NS)
    body = ElementTree.tostring(urlset, encoding="unicode")
    sitemap.write_text('<?xml version="1.0" encoding="UTF-8"?>\n' + body + "\n", encoding="utf-8")
    stats["sitemap"] = f"{before} -> {len(urlset.findall('sm:url', ns))} URLs"


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__.strip().split("\n")[0])
        print("usage: seo-postprocess.py <site-dir> <base-url>", file=sys.stderr)
        return 2
    site = Path(argv[1]).resolve()
    base = argv[2].rstrip("/")
    root = Path(__file__).resolve().parent.parent
    if not site.is_dir():
        print(f"not a directory: {site}", file=sys.stderr)
        return 1

    stats = {
        "processed": 0,
        "skipped": 0,
        "canonical": 0,
        "noindex": 0,
        "description": 0,
        "dublin_core": 0,
        "noindex_paths": set(),
    }
    for path in sorted(site.rglob("*.html")):
        process_page(root, site, path, base, stats)
    rewrite_sitemap(site, base, stats["noindex_paths"], stats)

    print(
        f"seo-postprocess: {stats['processed']} pages processed, "
        f"{stats['skipped']} skipped (not pkgdown or redirect), "
        f"{stats['canonical']} canonical links added, "
        f"{stats['noindex']} noindex tags added "
        f"({len(stats['noindex_paths'])} pages noindex in total), "
        f"{stats['description']} descriptions added, "
        f"{stats['dublin_core']} Dublin Core blocks added, "
        f"sitemap {stats['sitemap']}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
