// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// record_run_frame_cpp
SEXP record_run_frame_cpp(SEXP node);
RcppExport SEXP _maidr_record_run_frame_cpp(SEXP nodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type node(nodeSEXP);
    rcpp_result_gen = Rcpp::wrap(record_run_frame_cpp(node));
    return rcpp_result_gen;
END_RCPP
}
// heat_cell_rows_cpp
IntegerVector heat_cell_rows_cpp(IntegerVector sx, IntegerVector sy, int nx, int ny, IntegerVector cx, IntegerVector cy);
RcppExport SEXP _maidr_heat_cell_rows_cpp(SEXP sxSEXP, SEXP sySEXP, SEXP nxSEXP, SEXP nySEXP, SEXP cxSEXP, SEXP cySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type sx(sxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sy(sySEXP);
    Rcpp::traits::input_parameter< int >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< int >::type ny(nySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cx(cxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cy(cySEXP);
    rcpp_result_gen = Rcpp::wrap(heat_cell_rows_cpp(sx, sy, nx, ny, cx, cy));
    return rcpp_result_gen;
END_RCPP
}
// drop_empty_selectors_cpp
SEXP drop_empty_selectors_cpp(SEXP node, Function fallback);
RcppExport SEXP _maidr_drop_empty_selectors_cpp(SEXP nodeSEXP, SEXP fallbackSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< Function >::type fallback(fallbackSEXP);
    rcpp_result_gen = Rcpp::wrap(drop_empty_selectors_cpp(node, fallback));
    return rcpp_result_gen;
END_RCPP
}
// flatten_single_selectors_cpp
SEXP flatten_single_selectors_cpp(SEXP node, CharacterVector types, Function fallback, Function join);
RcppExport SEXP _maidr_flatten_single_selectors_cpp(SEXP nodeSEXP, SEXP typesSEXP, SEXP fallbackSEXP, SEXP joinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type types(typesSEXP);
    Rcpp::traits::input_parameter< Function >::type fallback(fallbackSEXP);
    Rcpp::traits::input_parameter< Function >::type join(joinSEXP);
    rcpp_result_gen = Rcpp::wrap(flatten_single_selectors_cpp(node, types, fallback, join));
    return rcpp_result_gen;
END_RCPP
}
// svg_trim_cpp
CharacterVector svg_trim_cpp(CharacterVector x);
RcppExport SEXP _maidr_svg_trim_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(svg_trim_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// svg_fmt_cpp
CharacterVector svg_fmt_cpp(NumericVector v);
RcppExport SEXP _maidr_svg_fmt_cpp(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(svg_fmt_cpp(v));
    return rcpp_result_gen;
END_RCPP
}
// svg_attr_cpp
CharacterVector svg_attr_cpp(CharacterVector lines, std::string name);
RcppExport SEXP _maidr_svg_attr_cpp(SEXP linesSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type lines(linesSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(svg_attr_cpp(lines, name));
    return rcpp_result_gen;
END_RCPP
}
// svg_flip_points_cpp
CharacterVector svg_flip_points_cpp(CharacterVector points, double h);
RcppExport SEXP _maidr_svg_flip_points_cpp(SEXP pointsSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(svg_flip_points_cpp(points, h));
    return rcpp_result_gen;
END_RCPP
}
// svg_flip_path_cpp
CharacterVector svg_flip_path_cpp(CharacterVector d, double h);
RcppExport SEXP _maidr_svg_flip_path_cpp(SEXP dSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(svg_flip_path_cpp(d, h));
    return rcpp_result_gen;
END_RCPP
}
// svg_style_attrs_cpp
CharacterVector svg_style_attrs_cpp(CharacterVector style, LogicalVector text, CharacterVector own, LogicalVector line, List gp_map, CharacterVector defaults, CharacterVector aliases, std::string sans);
RcppExport SEXP _maidr_svg_style_attrs_cpp(SEXP styleSEXP, SEXP textSEXP, SEXP ownSEXP, SEXP lineSEXP, SEXP gp_mapSEXP, SEXP defaultsSEXP, SEXP aliasesSEXP, SEXP sansSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type style(styleSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type text(textSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type own(ownSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type line(lineSEXP);
    Rcpp::traits::input_parameter< List >::type gp_map(gp_mapSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type defaults(defaultsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type aliases(aliasesSEXP);
    Rcpp::traits::input_parameter< std::string >::type sans(sansSEXP);
    rcpp_result_gen = Rcpp::wrap(svg_style_attrs_cpp(style, text, own, line, gp_map, defaults, aliases, sans));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_maidr_record_run_frame_cpp", (DL_FUNC) &_maidr_record_run_frame_cpp, 1},
    {"_maidr_heat_cell_rows_cpp", (DL_FUNC) &_maidr_heat_cell_rows_cpp, 6},
    {"_maidr_drop_empty_selectors_cpp", (DL_FUNC) &_maidr_drop_empty_selectors_cpp, 2},
    {"_maidr_flatten_single_selectors_cpp", (DL_FUNC) &_maidr_flatten_single_selectors_cpp, 4},
    {"_maidr_svg_trim_cpp", (DL_FUNC) &_maidr_svg_trim_cpp, 1},
    {"_maidr_svg_fmt_cpp", (DL_FUNC) &_maidr_svg_fmt_cpp, 1},
    {"_maidr_svg_attr_cpp", (DL_FUNC) &_maidr_svg_attr_cpp, 2},
    {"_maidr_svg_flip_points_cpp", (DL_FUNC) &_maidr_svg_flip_points_cpp, 2},
    {"_maidr_svg_flip_path_cpp", (DL_FUNC) &_maidr_svg_flip_path_cpp, 2},
    {"_maidr_svg_style_attrs_cpp", (DL_FUNC) &_maidr_svg_style_attrs_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_maidr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
