# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A run of flat records as a data frame, in C++
#'
#' The check [is_record_run()] makes and the columns [records_as_frames()]
#' builds, in one pass.
#'
#' @param node A non-empty list.
#' @return The data frame, `NULL` when `node` is not a run of flat records,
#'   or `NA` when it holds something only the R version decides (a pairlist
#'   record).
#' @keywords internal
#' @noRd
record_run_frame_cpp <- function(node) {
    .Call(`_maidr_record_run_frame_cpp`, node)
}

#' The source row each heatmap cell takes its value from, in C++
#'
#' For every requested cell, the first source row whose
#' `x == x_level & y == y_level` is not `FALSE`, as the per-cell scan it
#' replaces took it: a row whose x or y is missing compares `NA`, which
#' selects the row but not its value.
#'
#' @param sx,sy Each source row's x and y level (1-based), `0` for a value
#'   that equals no level and `NA` for a missing one.
#' @param nx,ny The number of x and y levels.
#' @param cx,cy The cells asked for, as x and y levels.
#' @return For each cell, the row as a positive index when it matched
#'   exactly, a negative one when it matched through a missing value, and
#'   `0` when no row matched.
#' @keywords internal
#' @noRd
heat_cell_rows_cpp <- function(sx, sy, nx, ny, cx, cy) {
    .Call(`_maidr_heat_cell_rows_cpp`, sx, sy, nx, ny, cx, cy)
}

#' drop_empty_selectors() over a whole payload, in C++
#'
#' @param node A maidr-data node.
#' @param fallback [drop_empty_selectors()], for a classed list or a
#'   pairlist, whose `$<-` and `[<-` the R version dispatches on.
#' @return As [drop_empty_selectors()].
#' @keywords internal
#' @noRd
drop_empty_selectors_cpp <- function(node, fallback) {
    .Call(`_maidr_drop_empty_selectors_cpp`, node, fallback)
}

#' flatten_single_selectors() over a whole payload, in C++
#'
#' @param node A maidr-data node.
#' @param types `SINGLE_SELECTOR_LAYER_TYPES`.
#' @param fallback [flatten_single_selectors()], for a classed list or a
#'   pairlist.
#' @param join [join_selector_list()], for a classed `selectors`.
#' @return As [flatten_single_selectors()].
#' @keywords internal
#' @noRd
flatten_single_selectors_cpp <- function(node, types, fallback, join) {
    .Call(`_maidr_flatten_single_selectors_cpp`, node, types, fallback, join)
}

#' svg_trim() in C++
#' @param x Character vector.
#' @return `x` without the trailing zeros of a decimal part.
#' @keywords internal
#' @noRd
svg_trim_cpp <- function(x) {
    .Call(`_maidr_svg_trim_cpp`, x)
}

#' svg_fmt() in C++
#' @param v Numeric vector.
#' @return Character vector, two places without trailing zeros.
#' @keywords internal
#' @noRd
svg_fmt_cpp <- function(v) {
    .Call(`_maidr_svg_fmt_cpp`, v)
}

#' svg_attr() in C++
#' @param lines Character vector of element lines.
#' @param name Attribute name.
#' @return Each line's attribute value, NA where it has none.
#' @keywords internal
#' @noRd
svg_attr_cpp <- function(lines, name) {
    .Call(`_maidr_svg_attr_cpp`, lines, name)
}

#' svg_flip_points() in C++
#' @param points Character vector of "x,y x,y" lists.
#' @param h Page height.
#' @return The lists with every y flipped about `h`.
#' @keywords internal
#' @noRd
svg_flip_points_cpp <- function(points, h) {
    .Call(`_maidr_svg_flip_points_cpp`, points, h)
}

#' svg_flip_path() in C++
#' @param d Character vector of absolute M/L/Z paths.
#' @param h Page height.
#' @return The paths with every y flipped about `h`.
#' @keywords internal
#' @noRd
svg_flip_path_cpp <- function(d, h) {
    .Call(`_maidr_svg_flip_path_cpp`, d, h)
}

#' svg_style_attrs() in C++
#'
#' @param style,text,own,line As for [svg_style_attrs()], all full length.
#' @param gp_map `svg_gp_attr_map`.
#' @param defaults `svg_style_defaults`.
#' @param aliases `svg_font_aliases()`.
#' @param sans The sans-serif font stack.
#' @return Character vector of attribute strings.
#' @keywords internal
#' @noRd
svg_style_attrs_cpp <- function(style, text, own, line, gp_map, defaults, aliases, sans) {
    .Call(`_maidr_svg_style_attrs_cpp`, style, text, own, line, gp_map, defaults, aliases, sans)
}

